language: scala
env:
  - PLAY_VERSION=2.2.0
before_script:
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
notifications:
  webhooks:
    - https://idobata.io/hook/48513d0f-dc38-408c-a441-c5be54ca6c28
